lowercaseKeywords: false
connections:
  - alias: postgres
    driver: postgresql
    proto: tcp
    user: postgres
    passwd: postgres
    host: localhost
    port: 5432
    dbName: postgres
    params:
      sslmode: disable
  - alias: clickhouse
    driver: clickhouse
    proto: tcp
    user: default
    passwd: default
    host: localhost
    port: 9000
    dbName: encord_analytics
