[settings]
experimental = true
lockfile = true

[tools]
# Languages go first
go = "1.25.4"
java = "openjdk-21.0.2"
lua = "5.4.8"
luajit = "2.1.ROLLING"
node = "22.17.1"
python = "3.11.13"
ruby = "3.4.7"
rust = "1.91.1"
terraform = "1.14.0"

# Then tools
argo-rollouts = "1.8.3"
awscli = "2.32.3"
bat = "0.26.0"
bat-extras = "2024.08.24"
bottom = "0.11.4"
chezmoi = "2.67.0"
clickhouse = "25.10.2.65-stable"
cmake = "4.2.0"
delta = "0.18.2"
direnv = "2.37.1"
duf = "0.9.1"
eza = "0.23.4"
fd = "10.3.0"
ffmpeg = "8.0.1"
firebase = "14.26.0"
fzf = "0.67.0"
gcloud = "548.0.0"
git-lfs = "3.7.1"
helm = "4.0.1"
jless = "0.9.0"
jq = "1.8.1"
kubecolor = "0.5.3"
kubectl = "1.34.2"
kubectx = "0.9.5"
liquibase = "4.33.0"
lua-language-server = "3.15.0"
make = "4.4.1"
ninja = "1.13.2"
postgres = "15.15"
pre-commit = "4.5.0"
ripgrep = "15.1.0"
semver = "3.4.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
starship = "1.24.1"
stylua = "2.3.1"
terraform-ls = "0.38.3"
tflint = "0.60.0"
tlrc = "1.12.0"
tmux = "3.5a"
tree-sitter = "0.25.10"
uv = "0.9.11"
yq = "4.49.2"
zoxide = "0.9.8"
