[settings]
experimental = true
lockfile = true

[tools]
argo-rollouts = "1.8.3"
awscli = "2.32.3"
clickhouse = "25.10.2.65-stable"
cmake = "4.2.0"
direnv = "2.37.1"
firebase = "14.26.0"
gcloud = "548.0.0"
go = "1.25.4"
helm = "4.0.0"
java = "openjdk-21.0.2"
kubecolor = "0.5.3"
kubectl = "1.34.2"
kubectx = "0.9.5"
lua = "5.4.8"
lua-language-server = "3.15.0"
make = "4.4.1"
ninja = "1.13.2"
node = "22.17.1"
postgres = "15.15"
pre-commit = "4.5.0"
python = "3.11.13"
ruby = "3.4.7"
rust = "1.91.1"
semver = "3.4.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.3.1"
terraform = "1.14.0"
terraform-ls = "0.38.2"
tflint = "0.60.0"
uv = "0.9.11"
