[settings]
experimental = true
lockfile = true

[tools]
# Languages go first
go = "1.25.6"
java = "openjdk-21.0.2"
lua = "5.5.0"
luajit = "2.1.ROLLING"
node = "22.17.1"
python = "3.12.12"
ruby = "4.0.1"
rust = "1.93.0"
terraform = "1.14.4"

# Then tools
1password = "2.32.0"
argo-rollouts = "1.8.3"
awscli = { version = "2.33.12", symlink_bins = "true" }
bat = "0.26.1"
bat-extras = "2024.08.24"
bottom = "0.12.3"
chezmoi = "2.69.3"
clickhouse = "25.12.4.35-stable"
cmake = "4.2.3"
curlie = "1.8.2"
delta = "0.18.2"
direnv = "2.37.1"
dotenvx = "1.52.0"
duf = "0.9.1"
eza = "0.23.4"
fd = "10.3.0"
ffmpeg = "8.0.1"
firebase = "15.5.1"
fzf = "0.67.0"
gcloud = "554.0.0"
gh = "2.86.0"
git-lfs = "3.7.1"
helm = "4.1.0"
jless = "0.9.0"
jq = "1.8.1"
kubecolor = "0.5.3"
kubectl = "1.35.0"
kubectx = "0.9.5"
kubens = "0.9.5"
liquibase = "4.33.0"
make = "4.4.1"
ninja = "1.13.2"
opencode = "1.1.48"
postgres = "15.15"
pre-commit = "4.5.1"
ripgrep = "15.1.0"
semver = "3.4.0"
starship = "1.24.2"
tlrc = "1.12.0"
tmux = "3.6"
tree-sitter = "0.26.5"
uv = "0.9.28"
yq = "4.52.2"
zoxide = "0.9.9"
