[settings]
experimental = true
lockfile = true

[tools]
# Languages go first
go = "1.25.6"
java = "openjdk-21.0.2"
lua = "5.4.8"
luajit = "2.1.ROLLING"
node = "22.17.1"
python = "3.12.12"
ruby = "4.0.1"
rust = "1.92.0"
terraform = "1.14.3"

# Then tools
argo-rollouts = "1.8.3"
awscli = { version = "2.33.4", symlink_bins = "true" }
bat = "0.26.1"
bat-extras = "2024.08.24"
bottom = "0.12.3"
chezmoi = "2.69.3"
clickhouse = "25.12.3.21-stable"
cmake = "4.2.2"
curlie = "1.8.2"
delta = "0.18.2"
direnv = "2.37.1"
duf = "0.9.1"
eza = "0.23.4"
fd = "10.3.0"
ffmpeg = "8.0.1"
firebase = "15.3.1"
fzf = "0.67.0"
gcloud = "553.0.0"
gh = "2.86.0"
git-lfs = "3.7.1"
helm = "4.1.0"
jless = "0.9.0"
jq = "1.8.1"
kubecolor = "0.5.3"
kubectl = "1.35.0"
kubectx = "0.9.5"
kubens = "0.9.5"
liquibase = "4.33.0"
make = "4.4.1"
ninja = "1.13.2"
opencode = "1.1.31"
postgres = "15.15"
pre-commit = "4.5.1"
ripgrep = "15.1.0"
semver = "3.4.0"
starship = "1.24.2"
tlrc = "1.12.0"
tmux = "3.6"
tree-sitter = "0.26.3"
uv = "0.9.26"
yq = "4.50.1"
zoxide = "0.9.8"
claude = { version = "2.1.15", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/stable" }
