[settings]
experimental = true
lockfile = true

[tools]
# Languages go first
go = "1.25.6"
java = "openjdk-21.0.2"
lua = "5.5.0"
luajit = "2.1.ROLLING"
node = "22.17.1"
python = "3.12.12"
ruby = "4.0.1"
rust = "1.93.0"
terraform = "1.14.4"
argo-rollouts = "1.8.3"
awscli = { version = "2.33.16", symlink_bins = "true" }
clickhouse = "25.12.4.35-stable"
cmake = "4.2.3"
dotenvx = "1.52.0"
duf = "0.9.1"
ffmpeg = "8.0.1"
firebase = "15.5.1"
gcloud = "555.0.0"
gh = "2.86.0"
helm = "4.1.0"
kubecolor = "0.5.3"
kubectl = "1.35.0"
kubectx = "0.9.5"
kubens = "0.9.5"
liquibase = "4.33.0"
make = "4.4.1"
ninja = "1.13.2"
opencode = "1.1.53"
postgres = "15.15"
pre-commit = "4.5.1"
semver = "3.4.0"
tree-sitter = "0.26.5"
uv = "0.10.0"

[tools."github:xjasonlyu/tun2socks"]
version = "2.6.0"
version_prefix = "v"
rename_exe = "tun2socks"
linux-x64 = { asset_pattern = "tun2socks-linux-amd64.zip", checksum = "sha256:2c4d9891ca898ecb2b582d158612d44c66793008328852b3465b77828c867e77" }
macos-arm64 = { asset_pattern = "tun2socks-darwin-arm64.zip", checksum = "sha256:4cf19ab928e36ced549c52be78d1d2dd0bb52f6cd77f6475e25bfa1c7c3327c1" }
